#!/bin/bash

DATETIME=`date`
VERSION=`date +%s`
npm run clean && npm run generate && npm run deploy

#git add --all . && git commit -m "regular build\n\nbuild on $DATETIME" && git push origin master

cd ../blog4daocloud && echo $DATETIME >> buildtime && \
  git add --all . && \
  git commit -m "regular build\n\nbuild on $DATETIME" && \
  git push origin master && \
  git tag "v$VERSION" && git push origin "v$VERSION"
